services:
  
  #PHP Service
  laravel-crud-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-crud-app
    container_name: laravel-crud-app
    restart: unless-stopped
    depends_on:
      - laravel-crud-db
    tty: true
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-app-network

  #Nginx Service
  laravel-crud-webserver:
    image: nginx:alpine
    container_name: laravel-crud-webserver
    restart: unless-stopped
    depends_on:
      - laravel-crud-app
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - laravel-app-network

  #MySQL Service
  laravel-crud-db:
    image: mysql:5.7.22
    container_name: laravel-crud-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_crud_app
      MYSQL_ROOT_PASSWORD: rootPassword123
    volumes:
      - laravel_crud_app_db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-app-network
  
  laravel-crud-phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - laravel-crud-db
    ports:
      - 8080:80
    environment:
      - PMA_HOST=laravel-crud-db
    networks:
      - laravel-app-network

#Docker Networks
networks:
  laravel-app-network:
    driver: bridge

#Volumes
volumes:
  laravel_crud_app_db_data:
    driver: local